	nios_system u0 (
		.clk_clk                           (<connected-to-clk_clk>),                           //                     clk.clk
		.keycode_export                    (<connected-to-keycode_export>),                    //                 keycode.export
		.onchip_memory2_0_reset1_reset     (<connected-to-onchip_memory2_0_reset1_reset>),     // onchip_memory2_0_reset1.reset
		.onchip_memory2_0_reset1_reset_req (<connected-to-onchip_memory2_0_reset1_reset_req>), //                        .reset_req
		.onchip_memory2_0_s1_address       (<connected-to-onchip_memory2_0_s1_address>),       //     onchip_memory2_0_s1.address
		.onchip_memory2_0_s1_debugaccess   (<connected-to-onchip_memory2_0_s1_debugaccess>),   //                        .debugaccess
		.onchip_memory2_0_s1_clken         (<connected-to-onchip_memory2_0_s1_clken>),         //                        .clken
		.onchip_memory2_0_s1_chipselect    (<connected-to-onchip_memory2_0_s1_chipselect>),    //                        .chipselect
		.onchip_memory2_0_s1_write         (<connected-to-onchip_memory2_0_s1_write>),         //                        .write
		.onchip_memory2_0_s1_readdata      (<connected-to-onchip_memory2_0_s1_readdata>),      //                        .readdata
		.onchip_memory2_0_s1_writedata     (<connected-to-onchip_memory2_0_s1_writedata>),     //                        .writedata
		.onchip_memory2_0_s1_byteenable    (<connected-to-onchip_memory2_0_s1_byteenable>),    //                        .byteenable
		.otg_hpi_address_export            (<connected-to-otg_hpi_address_export>),            //         otg_hpi_address.export
		.otg_hpi_cs_export                 (<connected-to-otg_hpi_cs_export>),                 //              otg_hpi_cs.export
		.otg_hpi_data_in_port              (<connected-to-otg_hpi_data_in_port>),              //            otg_hpi_data.in_port
		.otg_hpi_data_out_port             (<connected-to-otg_hpi_data_out_port>),             //                        .out_port
		.otg_hpi_r_export                  (<connected-to-otg_hpi_r_export>),                  //               otg_hpi_r.export
		.otg_hpi_reset_export              (<connected-to-otg_hpi_reset_export>),              //           otg_hpi_reset.export
		.otg_hpi_w_export                  (<connected-to-otg_hpi_w_export>),                  //               otg_hpi_w.export
		.reset_reset_n                     (<connected-to-reset_reset_n>),                     //                   reset.reset_n
		.sdram_clk_clk                     (<connected-to-sdram_clk_clk>),                     //               sdram_clk.clk
		.sdram_wire_addr                   (<connected-to-sdram_wire_addr>),                   //              sdram_wire.addr
		.sdram_wire_ba                     (<connected-to-sdram_wire_ba>),                     //                        .ba
		.sdram_wire_cas_n                  (<connected-to-sdram_wire_cas_n>),                  //                        .cas_n
		.sdram_wire_cke                    (<connected-to-sdram_wire_cke>),                    //                        .cke
		.sdram_wire_cs_n                   (<connected-to-sdram_wire_cs_n>),                   //                        .cs_n
		.sdram_wire_dq                     (<connected-to-sdram_wire_dq>),                     //                        .dq
		.sdram_wire_dqm                    (<connected-to-sdram_wire_dqm>),                    //                        .dqm
		.sdram_wire_ras_n                  (<connected-to-sdram_wire_ras_n>),                  //                        .ras_n
		.sdram_wire_we_n                   (<connected-to-sdram_wire_we_n>),                   //                        .we_n
		.onchip_memory_1_s1_address        (<connected-to-onchip_memory_1_s1_address>),        //      onchip_memory_1_s1.address
		.onchip_memory_1_s1_debugaccess    (<connected-to-onchip_memory_1_s1_debugaccess>),    //                        .debugaccess
		.onchip_memory_1_s1_clken          (<connected-to-onchip_memory_1_s1_clken>),          //                        .clken
		.onchip_memory_1_s1_chipselect     (<connected-to-onchip_memory_1_s1_chipselect>),     //                        .chipselect
		.onchip_memory_1_s1_write          (<connected-to-onchip_memory_1_s1_write>),          //                        .write
		.onchip_memory_1_s1_readdata       (<connected-to-onchip_memory_1_s1_readdata>),       //                        .readdata
		.onchip_memory_1_s1_writedata      (<connected-to-onchip_memory_1_s1_writedata>),      //                        .writedata
		.onchip_memory_1_s1_byteenable     (<connected-to-onchip_memory_1_s1_byteenable>),     //                        .byteenable
		.onchip_memory_1_reset1_reset      (<connected-to-onchip_memory_1_reset1_reset>),      //  onchip_memory_1_reset1.reset
		.onchip_memory_1_reset1_reset_req  (<connected-to-onchip_memory_1_reset1_reset_req>),  //                        .reset_req
		.onchip_memory_0_reset1_reset      (<connected-to-onchip_memory_0_reset1_reset>),      //  onchip_memory_0_reset1.reset
		.onchip_memory_0_reset1_reset_req  (<connected-to-onchip_memory_0_reset1_reset_req>),  //                        .reset_req
		.onchip_memory_0_s1_address        (<connected-to-onchip_memory_0_s1_address>),        //      onchip_memory_0_s1.address
		.onchip_memory_0_s1_debugaccess    (<connected-to-onchip_memory_0_s1_debugaccess>),    //                        .debugaccess
		.onchip_memory_0_s1_clken          (<connected-to-onchip_memory_0_s1_clken>),          //                        .clken
		.onchip_memory_0_s1_chipselect     (<connected-to-onchip_memory_0_s1_chipselect>),     //                        .chipselect
		.onchip_memory_0_s1_write          (<connected-to-onchip_memory_0_s1_write>),          //                        .write
		.onchip_memory_0_s1_readdata       (<connected-to-onchip_memory_0_s1_readdata>),       //                        .readdata
		.onchip_memory_0_s1_writedata      (<connected-to-onchip_memory_0_s1_writedata>),      //                        .writedata
		.onchip_memory_0_s1_byteenable     (<connected-to-onchip_memory_0_s1_byteenable>)      //                        .byteenable
	);

